import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:flutter_screenutil/flutter_screenutil.dart';
import 'package:firebase_core/firebase_core.dart';

import 'core/ads/ad_service.dart';
import 'core/config/app_config.dart';
import 'core/notifications/notification_service.dart';
import 'core/responsive/responsive_helper.dart';
import 'core/theme/app_theme.dart';
import 'core/theme/theme_provider.dart';
import 'features/subscriptions/presentation/home_shell.dart';

Future<void> main() async {
  WidgetsFlutterBinding.ensureInitialized();

  // Initialize Firebase if configured
  if (AppConfig.isFirebaseConfigured) {
    try {
      await Firebase.initializeApp(
          // Firebase options will be generated by flutterfire_cli
          // Run: flutterfire configure
          // This will create firebase_options.dart with proper configuration
          );
    } catch (e) {
      // Firebase not fully configured yet - app will work in offline mode
      // The error is expected if firebase_options.dart doesn't exist
      print('Firebase initialization skipped: $e');
    }
  }

  final notificationService = LocalNotificationService();
  await notificationService.initialize();

  // Initialize ads
  await AdService.initialize();

  runApp(
    ProviderScope(
      overrides: [
        notificationServiceProvider.overrideWithValue(notificationService),
      ],
      child: const SubscriptionsApp(),
    ),
  );
}

class SubscriptionsApp extends ConsumerWidget {
  const SubscriptionsApp({super.key});

  @override
  Widget build(BuildContext context, WidgetRef ref) {
    final themeState = ref.watch(themeProvider);

    return ScreenUtilInit(
      designSize: const Size(
        ResponsiveHelper.designWidth,
        ResponsiveHelper.designHeight,
      ),
      minTextAdapt: true,
      splitScreenMode: true,
      builder: (context, child) {
        return MaterialApp(
          title: 'Subscriptions',
          debugShowCheckedModeBanner: false,
          theme: AppTheme.build(themeState, context),
          darkTheme: AppTheme.build(themeState, context),
          themeMode: themeState.brightness == Brightness.dark
              ? ThemeMode.dark
              : ThemeMode.light,
          home: const HomeShell(),
          builder: (context, widget) {
            return MediaQuery(
              data: MediaQuery.of(context).copyWith(
                textScaleFactor: ResponsiveHelper.textScaleFactor(context),
              ),
              child: widget!,
            );
          },
        );
      },
    );
  }
}
