import 'package:firebase_core/firebase_core.dart';
import '../../firebase_options.dart';
import 'dev_config.dart';

/// App configuration with API keys and feature flags
///
/// Firebase configuration is loaded from firebase_options.dart
/// which is generated by FlutterFire CLI (flutterfire configure)
class AppConfig {
  // Vercel Proxy Server URL
  static const String vercelProxyUrl =
      'YOUR_VERCEL_PROXY_URL'; // e.g., https://your-app.vercel.app/api

  // Firebase Configuration
  // These values are loaded from firebase_options.dart
  static FirebaseOptions? get firebaseOptions =>
      DefaultFirebaseOptions.currentPlatform;

  static String? get firebaseApiKey => firebaseOptions?.apiKey;
  static String? get firebaseAppId => firebaseOptions?.appId;
  static String? get firebaseProjectId => firebaseOptions?.projectId;
  static String? get firebaseMessagingSenderId =>
      firebaseOptions?.messagingSenderId;
  static String? get firebaseStorageBucket => firebaseOptions?.storageBucket;

  // Feature Flags
  static const bool enableEmailScanner = true;
  static const bool enableSmsScanner = true;
  static const bool enableReceiptUpload = true;
  static const bool enableCloudSync = true;
  static const bool enableAiInsights = true;

  // Check if API keys are configured
  static bool get isVercelProxyConfigured =>
      vercelProxyUrl != 'YOUR_VERCEL_PROXY_URL';

  /// Check if Firebase is properly configured
  /// Returns true if firebase_options.dart exists and has valid configuration
  static bool get isFirebaseConfigured {
    try {
      final options = firebaseOptions;
      return options != null &&
          options.apiKey.isNotEmpty &&
          options.projectId.isNotEmpty &&
          options.appId.isNotEmpty;
    } catch (e) {
      // firebase_options.dart might not exist or be misconfigured
      return false;
    }
  }

  /// Initialize Firebase with the configured options
  /// This should be called in main() before runApp()
  static Future<void> initializeFirebase() async {
    if (!isFirebaseConfigured) {
      throw Exception(
        'Firebase is not configured. Run "flutterfire configure" to set up Firebase.',
      );
    }

    try {
      await Firebase.initializeApp(
        options: firebaseOptions,
      );
    } catch (e) {
      throw Exception('Failed to initialize Firebase: $e');
    }
  }
}
